surepass.api.base-url=https://sandbox.surepass.io/api/v1
surepass.api.token=YOUR_SUREPASS_TOKEN

spring.application.name=surepass-orchestrator-service
server.port=8080
server.servlet.context-path=/surepass-orchestrator

